//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cargo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargo_Detail
    {
        public int CargoId { get; set; }
        public string Email_ID { get; set; }
        public string Password { get; set; }
        public string OwnerName { get; set; }
        public string CompanyName { get; set; }
        public string CompAddress { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string Phone { get; set; }
        public string WorkCategory { get; set; }
        public string ImageName { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string Longitude { get; set; }
        public string latitude { get; set; }
    }
}
