//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cargo
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Cargo_Request_Item
    {
        public int ItemId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> RequestId { get; set; }
        public string Item_Name { get; set; }
        public string Qty { get; set; }
    }
}
